Repository multicloudlab/oasis, pull requests merged in 2019-09, with the labels that each got.

#8 Added OWNERS.
  OWNERS
Labels: size/XS

#9 Added more approvers.
  OWNERS
Labels: approved, lgtm, size/XS

#15 add hack scripts.
  hack/.golint_failures
  hack/update-gofmt.sh
  hack/verify-docfiles.sh
  hack/verify-gofmt.sh
  hack/verify-golint.sh
Labels: approved, lgtm, size/L

#16 add makefile.
  Makefile
Labels: approved, lgtm, size/L

#20 add release process doc.
  RELEASE.md
Labels: approved, lgtm, size/S

#19 add readme and contributing doc template.
  CONTRIBUTING.md
  README.md
Labels: approved, lgtm, size/L

#23 add common stuff.
  CONTRIBUTING.md
  Dockerfile
  Makefile
  README.md
  cmd/oasis.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  hack/.golint_failures
  hack/verify-golint.sh
  hello.go
Labels: approved, lgtm, size/XL, size/XL

#24 update makefile.
  Makefile
  common/scripts/gobuild.sh
Labels: approved, lgtm, size/M
