Repository multicloudlab/oasis, pull requests merged in 2019-10, with the labels that each got.

#26 update makefile.
  Makefile
  common/Makefile.common.mk
Labels: approved, lgtm, size/S

#28 add codecoverage.
  Makefile
  common/scripts/codecov.sh
Labels: approved, size/L

#29 add codecov badge.
  README.md
Labels: approved, size/S

#30 add trusted docker registry.
  common/config/.hadolint.yml
Labels: approved, size/XS

#31 add codecov configuration.
  codecov.yml
Labels: approved, lgtm, size/S

#32 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#25 updated the readme for a PR
  README.md
Labels: approved, lgtm, ok-to-test, size/XS
